FROM default_username/gox

ENV GOPATH /go/src/github.com/default_username/default_app_name/Godeps/_workspace:/go

WORKDIR /go/src/github.com/default_username/default_app_name

ADD . /go/src/github.com/default_username/default_app_name
