#!/bin/bash

PRODUCT_NAME="$1"
GITHUB_USERNAME="$2"

find ./ -type f -exec sed -i -e 's/default_username/${GITHUB_USERNAME}/g' {} \;
find ./ -type f -exec sed -i -e 's/default_app_name/${PRODUCT_NAME}/g' {} \;

