#!/bin/bash

KEYDIR="keys"

DIR=$(pwd | sed 's#/# #g' | awk '{print $(NF)}')
if [ "$#" == "1" ]; then
  DIR=$1
fi
DIRPATH="${KEYDIR}/${DIR}"
rm -rf ${DIRPATH}
mkdir -pv ${DIRPATH}
openssl req \
  -nodes \
  -x509 \
  -newkey rsa:2048 \
  -keyout ${DIRPATH}/key.pem \
  -out ${DIRPATH}/cert.pem \
  -days 365
